### PR TITLE
Allow find date

### PR DESCRIPTION
**Pull request by bokun2**

### CODE REVIEW

**Comment by bokun2** [comment]
Command: find yyyy-mm-dd/find yyyy-mm/find yyyy

**Review by ZhengLong3 — COMMENTED** [review]
LGTM

**Comment by ngquyduc** [comment]
Do you think it might be better if we only allow Find to find name and description? Date should be find using a separate Command like FilterTag and FilterStatus.

**Comment by bokun2** [comment]
> Do you think it might be better if we only allow Find to find name and description? Date should be find using a separate Command like FilterTag and FilterStatus.

I try to fix it later

**Pull request merged**
