### PR TITLE
Update UG & DG

### PR DESCRIPTION
**Pull request by ssyap98**
- Please help me check the DG and tell me what to change 😢😢😢. I mentioned the implementation of the status field and the sequence diagram is showing what happens when the user perform the add command. 

- The screenshots for the UG I follow the examples in Zheng Long's PR. Let me know if the screenshots are okay or not!

### CODE REVIEW

**Review by ZhengLong3 — COMMENTED** [review]
LGTM, but it seems like you added the screenshots but did not link them to the UG? And I think some of the pictures might be unnecessary, especially findStatus and findTag since they are similar to find.

**Comment by ssyap98** [comment]
> LGTM, but it seems like you added the screenshots but did not link them to the UG? And I think some of the pictures might be unnecessary, especially findStatus and findTag since they are similar to find.

Are you gonna resolve the merge conflicts afterwards? Then I shall link the screenshots to the UG first. Is there any other commands that you think require screenshots?

And the DG is okay?

**Comment by ZhengLong3** [comment]
Yeah, the DG looks ok, actually if you all are happy with the UG can merge also

**Comment by ssyap98** [comment]
Oh ya actually if you look at the sequence diagram. Do you know what is suppose to be the parameter for the addActivity method?

**Pull request merged**
